import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import '../styles/main.css'

const poppins = Outfit({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-poppins',
  weight: ['100','200','300','400', '500', '600', '700','800']
});

export const metadata: Metadata = {
  title: 'Horixons',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`display-nones w-full h-screen ${poppins.className}`}>{children}</body>
    </html>
  )
}
